name = "DecisionTreeSoleInterface"
uuid = "de8eae22-3630-40e0-868c-abfc4c1bb3da"
authors = ["Giovanni Pagliarini"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
